-keep class com.crownos.connect.llts.Llts { native <methods>; }
-keep class com.crownos.fileshare.ffsp.Ffsp { native <methods>; }
-keepclasseswithmembernames class * { native <methods>; }
-keepattributes *Annotation*, InnerClasses, Signature
-keep,includedescriptorclasses class com.crownos.connect.**$$serializer { *; }
-keepclassmembers class com.crownos.connect.** { *** Companion; }
-keep class android.hardware.input.IInputManager** { *; }
-keep class android.content.IClipboard** { *; }
-keep class android.net.ITetheringConnector** { *; }
-dontwarn android.**
